name: plantaoflex
description: "A new Flutter project."
publish_to: 'none' # Remove esta linha se deseja publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Ícones do estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  # Para usar ícones do Material
  uses-material-design: true

  # Seção de assets - Adicione seus assets aqui
  assets:
    - images/logo_plantaoFlex.png
