// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Z2_34uJl0dcTOIhaje0EebIQEj1hZ_Y',
    appId: '1:20801902208:android:2bde57ba3b4e8c36187865',
    messagingSenderId: '20801902208',
    projectId: 'plantaoflex-e7d31',
    storageBucket: 'plantaoflex-e7d31.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEzuNIkEBdhgPGEDH7lDBus2ckvMna8BQ',
    appId: '1:20801902208:web:30ec58f687bbeb08187865',
    messagingSenderId: '20801902208',
    projectId: 'plantaoflex-e7d31',
    authDomain: 'plantaoflex-e7d31.firebaseapp.com',
    storageBucket: 'plantaoflex-e7d31.appspot.com',
    measurementId: 'G-G7RGFXG6T0',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEzuNIkEBdhgPGEDH7lDBus2ckvMna8BQ',
    appId: '1:20801902208:web:30ec58f687bbeb08187865',
    messagingSenderId: '20801902208',
    projectId: 'plantaoflex-e7d31',
    authDomain: 'plantaoflex-e7d31.firebaseapp.com',
    storageBucket: 'plantaoflex-e7d31.appspot.com',
    measurementId: 'G-G7RGFXG6T0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwze7-d_2qRU10kqWW79RiW68LgV5RNoo',
    appId: '1:20801902208:ios:f832d7364bcb0b6a187865',
    messagingSenderId: '20801902208',
    projectId: 'plantaoflex-e7d31',
    storageBucket: 'plantaoflex-e7d31.appspot.com',
    iosBundleId: 'com.example.plantaoflex',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwze7-d_2qRU10kqWW79RiW68LgV5RNoo',
    appId: '1:20801902208:ios:f832d7364bcb0b6a187865',
    messagingSenderId: '20801902208',
    projectId: 'plantaoflex-e7d31',
    storageBucket: 'plantaoflex-e7d31.appspot.com',
    iosBundleId: 'com.example.plantaoflex',
  );

}